[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_only = false
style = "bold purple"

[username]
format = "[$user]($style)@"
show_always = true
style_user = "bold yellow"

[directory]
read_only = " ðŸ”’"
truncation_symbol = "â€¦/"

[character]
error_symbol = "[ & ](bold red)"
success_symbol = "[ & ](bold green)"

# Battery check takes ~66ms
[battery]
disabled = true
